#:kivy 1.8.0
#:import tr __main__.tr

BoxLayout:
    orientation: 'vertical'

    Label:
        text: tr._('Hello World')

    BoxLayout:
        size_hint_y: None
        height: '48dp'
        spacing: '2dp'
        padding: '3dp'

        Button:
            text: tr._('French')
            on_release: app.lang = 'fr'

        Button:
            text: tr._('English')
            on_release: app.lang = 'en'
